# Generated by Django 6.0.6 on 2026-07-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_team_receiver_role_invite',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='message',
        ),
    ]
