# Generated by Django 6.0.6 on 2026-07-13 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_invitation_invite_sender_not_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['receiver', '-id'], name='teams_invit_receive_bc473d_idx'),
        ),
    ]
