# Generated by Django 6.0.6 on 2026-07-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['updated_at']},
        ),
    ]
